### ISSUE TITLE
Work without browserify/webpack?

### ISSUE THREAD

**Issue by Martin-Pitt** [jamen-archive/vss#2]
This is just a feature request, feel free to reject, accept or interpret, but I'd love to be able to use this without having to go through browserify or webpack.

My ideal would be to use it in a vanilla site like so:

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="initial-scale=1, width=device-width">
	<link rel="stylesheet" href="css/unstyle.css">
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/dynamic.css" type="text/vss">
	<script src="js/vss.js"></script>
	<script src="js/app.js"></script>

<body>
	<div class="foo"></div>
```

dynamic.css
```
div.foo {
	width: #{bar}%;
	transition: width 200ms ease-in-out;
}
```

app.js
```
var css = vss.register({ bar: '5%' });
css.bar = '100%';
```

**Comment by jamen** [comment]
I agree, this would be a nice alternative way to use `vss`.

One simple thing you could probably do is:
```
// vss.js:
window.vss = require('vss');
```
Then bundle this with Browserify/Webpack, then you could `<script>` it:
```
<script src="vss.js"></script>
```

I'm a bit uneasy about prebundling dist files, because I would have to ship them with the dependencies concatenated in the source, and I'd basically be shipping other people's code.
